Documentation:
    Enabled: false
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/*'
    - 'db/migrate/*'
    - 'config/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'vendor/bundle/**/*'
